In [1]:
import tensorflow as tf

In [2]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'D:\\anaconda\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


 TENSORS

In [6]:
string = tf.Variable('Prameet',tf.string)
num = tf.Variable(1106,tf.int16)

In [27]:
tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [7]:
#Rank of tensors
rank_1_tensor = tf.Variable(['Prameet','1106'],tf.string)

In [8]:
rank_2_tensor = tf.Variable([['Prashant','1107'],['Prameet','1106']],tf.string)

In [15]:
tf.rank(rank_1_tensor)


<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [16]:
tf.rank(rank_2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [17]:
#shapes of tensor
rank_1_tensor.shape

TensorShape([2])

In [18]:
rank_2_tensor.shape

TensorShape([2, 2])

In [19]:
t1 =tf.ones([1,2,3])

In [20]:
#changing shape
t2 = tf.reshape(t1,[2,3,1])

In [21]:
print(t1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [22]:
print(t2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [23]:
t3 = tf.reshape(t1,[3,-1])

In [25]:
print(t3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [51]:
a = tf.constant(7)
b = tf.constant(8)

In [52]:
tf.print(a+b)

15


In [34]:
const = tf.constant(10)

In [35]:
fill_mat = tf.fill((4,4),10)

In [36]:
zeros = tf.zeros((4,4))
ones = tf.ones((4,4))

In [39]:
randn = tf.random.normal((4,4),mean=0,stddev=1)

In [57]:
randu = tf.random.uniform((4,4),minval=0,maxval=1)

In [41]:
zeros

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [42]:
tf.print(zeros*ones)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [43]:
tf.print(randn)

[[0.987793803 1.13582373 1.42735648 0.498756766]
 [0.133504316 -1.63901305 1.77280796 -0.066622071]
 [-0.512644947 -1.5706284 0.320747226 0.180636331]
 [0.139723152 0.51674962 0.228682011 -1.14733601]]


In [44]:
a = tf.constant([[1,2],
                 [3,4]])

In [45]:
a.shape

TensorShape([2, 2])

In [46]:
b = tf.constant([[10],
                 [100]])

In [47]:
b.shape

TensorShape([2, 1])

In [50]:
print(tf.matmul(a,b))

tf.Tensor(
[[210]
 [430]], shape=(2, 1), dtype=int32)


In [58]:
randu

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.8527492 , 0.24671483, 0.91290486, 0.6417724 ],
       [0.3981732 , 0.92306566, 0.9595978 , 0.81887674],
       [0.18782866, 0.9457263 , 0.8535509 , 0.5153438 ],
       [0.5488645 , 0.7689625 , 0.44320428, 0.35148227]], dtype=float32)>

In [59]:
var = tf.Variable(randu)

In [60]:
var

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[0.8527492 , 0.24671483, 0.91290486, 0.6417724 ],
       [0.3981732 , 0.92306566, 0.9595978 , 0.81887674],
       [0.18782866, 0.9457263 , 0.8535509 , 0.5153438 ],
       [0.5488645 , 0.7689625 , 0.44320428, 0.35148227]], dtype=float32)>